Repository SacOverflow/CAMEL-Services, pull requests merged in 2024-03, with the labels that each got.

#27 SO-86
  .gitignore
  __tests__/routes/Login.test.tsx
  jest.config.ts
  package-lock.json
  src/components/Login/LoginForm.tsx
  src/components/RecoverPassword/RecoverPasswordForm.tsx
  src/components/SharedComponents/InputComponent.tsx
  src/components/SignUp/SignUpForm.tsx
  src/components/UpdatePassword/UpdatePasswordForm.tsx
  src/lib/actions/auth.client.ts
Labels: feature, testing

#35 SO-87
  src/app/(dashboard)/invoices/page.tsx
  src/app/(dashboard)/projects/[id]/page.tsx
  src/components/Invoices/ProjectReceiptList/recieptList.tsx
  src/components/Invoices/ProjectsItemList/itemsList.tsx
  src/components/Invoices/index.tsx
  src/components/projects/ProjectReciept/ProjectReciepts.css
  src/components/projects/ProjectReciept/index.tsx
  src/types/database.interface.ts
Labels: feature

#36 SO-115
  src/app/(auth)/base.css
  src/app/(dashboard)/dashboard/DashboardPage.css
  src/app/(dashboard)/projects/[id]/SingleProjectPage.css
  src/app/globals.css
  src/app/page.tsx
  src/components/Account/AccountInputField/AccountInputField.css
  src/components/Account/AccountInputField/AccountInputField.tsx
  src/components/Account/Inputfield/Inputfield.tsx
  src/components/Dashboard/Monthly_Spending/MonthlySpend.tsx
  src/components/Dashboard/Monthly_Spending/MonthlySpending.css
  src/components/HomePage/Card.css
  src/components/HomePage/Card.tsx
  src/components/HomePage/Testimonial.css
  src/components/HomePage/Testimonial.tsx
  src/components/SharedComponents/Footer.tsx
  src/components/SignUp/SignUpForm.tsx
  src/components/projects/ProjectReciept/ProjectReciepts.css
  src/components/projects/ProjectReciept/index.tsx
  src/components/projects/ProjectTasks/ProjectTask.css
  src/components/projects/ProjectTasks/TaskCard/index.tsx
  src/components/projects/ProjectTasks/client.tsx
  src/lib/actions/auth.client.ts
  src/types/auth.constants.ts
Labels: feature

#42 tests for create and read org
  __tests__/routes/Organizations.test.tsx
  package-lock.json
  package.json
  src/components/Organization/CreateOrgModal.tsx
  src/components/Organization/client.actions.ts
Labels: testing
